### PR TITLE
Boost super-project tests target

### LINKED ISSUE #53: Boost CMake testing procedure doesn't work for StaticString
The [documented testing procedure](https://github.com/boostorg/cmake#testing-boost-with-cmake)

```
mkdir __build && cd __build
cmake -DBUILD_TESTING=ON -DBOOST_INCLUDE_LIBRARIES=static_string ..
cmake --build . --target tests
ctest --output-on-failure --no-tests=error
```

fails for Boost.StaticString, because the test executables aren't built by the target `tests`. BoostTest handles this automatically, but for tests declared manually, one needs to first declare the `tests` target if not present

```
if(NOT TARGET tests)
    add_custom_target(tests)
endif()
```

and then for each test executable, use `add_dependencies(test my_test_executable)`.

Or, since there is already a target `boost_static_string_all_tests`, it should be enough to make it a dependency of `tests`: `add_dependencies(tests boost_static_string_all_tests)`.

(For this to keep working after the eventual fix, it might be a good idea to add it to CI.)

It's also good practice to make the test executables EXCLUDE_FOR_ALL, so that building the `tests` target builds them, but building the default target doesn't, but this step is not in principle required.

### PR DESCRIPTION
**Pull request by alandefreitas**
fix #53

### CODE REVIEW

**Comment by pdimov** [comment]
Should fix it. But you have to add it to CI as well.

**Comment by alandefreitas** [comment]
Yes. I noticed CI is a mess. CMake is being tested in Drone but it still needs to be fixed. 

I'll have to do it in another PR because I can't start another CI marathon this close to Christmas.

**Review by sdkrystian — APPROVED** [review]
@alandefreitas LGTM

**Comment by pdimov** [comment]
This doesn't seem to have been merged to master. Please merge.

**Pull request merged**
